builds:
  - id: otfd
    ldflags:
    - -s -w
    - -X github.com/tofutf/tofutf/internal.Version={{.Version}}
    - -X github.com/tofutf/tofutf/internal.Commit={{.Commit}}
    - -X github.com/tofutf/tofutf/internal.Built={{.Date}}
    main: ./cmd/otfd
    binary: otfd
    env:
      - CGO_ENABLED=0
    goos:
    - linux
    goarch:
    - 386
    - amd64
    - arm64
  - id: otf-agent
    ldflags:
    - -s -w
    - -X github.com/tofutf/tofutf/internal.Version={{.Version}}
    - -X github.com/tofutf/tofutf/internal.Commit={{.Commit}}
    - -X github.com/tofutf/tofutf/internal.Built={{.Date}}
    main: ./cmd/otf-agent
    binary: otf-agent
    env:
      - CGO_ENABLED=0
    goos:
    - linux
    goarch:
    - 386
    - amd64
    - arm64
  - id: otf
    ldflags:
    - -s -w
    - -X github.com/tofutf/tofutf/internal.Version={{.Version}}
    - -X github.com/tofutf/tofutf/internal.Commit={{.Commit}}
    - -X github.com/tofutf/tofutf/internal.Built={{.Date}}
    main: ./cmd/otf
    binary: otf
    env:
      - CGO_ENABLED=0
    goos:
    - darwin
    - linux
    goarch:
    - 386
    - amd64
    - arm64
archives:
- id: otfd
  builds:
    - otfd
  format: zip
  name_template: "otfd_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
- id: otf-agent
  builds:
    - otf-agent
  format: zip
  name_template: "otf-agent_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
- id: otf
  builds:
    - otf
  format: zip
  name_template: "otf_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
dockers:
- goos: linux
  goarch: amd64
  ids:
  - otfd
  image_templates:
  - "ghcr.io/tofutf/tofutfd:latest-amd64"
  - "ghcr.io/tofutf/tofutfd:{{ .Version }}-amd64"
  skip_push: auto
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - "--pull"
  - "--platform=linux/amd64"
- goos: linux
  goarch: arm64
  ids:
  - otfd
  image_templates:
  - "ghcr.io/tofutf/tofutfd:latest-arm64"
  - "ghcr.io/tofutf/tofutfd:{{ .Version }}-arm64"
  skip_push: auto
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - "--pull"
  - "--platform=linux/arm64"
- goos: linux
  goarch: amd64
  ids:
  - otf-agent
  image_templates:
  - "ghcr.io/tofutf/tofutf-agent:latest-amd64"
  - "ghcr.io/tofutf/tofutf-agent:{{ .Version }}-amd64"
  skip_push: auto
  dockerfile: Dockerfile.agent
  use: buildx
  build_flag_templates:
  - "--pull"
  - "--platform=linux/amd64"
- goos: linux
  goarch: arm64
  ids:
  - otf-agent
  image_templates:
  - "ghcr.io/tofutf/tofutf-agent:latest-arm64"
  - "ghcr.io/tofutf/tofutf-agent:{{ .Version }}-arm64"
  skip_push: auto
  dockerfile: Dockerfile.agent
  use: buildx
  build_flag_templates:
  - "--pull"
  - "--platform=linux/arm64"
docker_manifests:
- name_template: 'ghcr.io/tofutf/tofutfd:latest'
  image_templates:
  - "ghcr.io/tofutf/tofutfd:latest-amd64"
  - "ghcr.io/tofutf/tofutfd:latest-arm64"
- name_template: 'ghcr.io/tofutf/tofutfd:{{ .Version }}'
  image_templates:
  - "ghcr.io/tofutf/tofutfd:{{ .Version }}-amd64"
  - "ghcr.io/tofutf/tofutfd:{{ .Version }}-arm64"
- name_template: 'ghcr.io/tofutf/tofutf-agent:latest'
  image_templates:
  - "ghcr.io/tofutf/tofutf-agent:latest-amd64"
  - "ghcr.io/tofutf/tofutf-agent:latest-arm64"
- name_template: 'ghcr.io/tofutf/tofutf-agent:{{ .Version }}'
  image_templates:
  - "ghcr.io/tofutf/tofutf-agent:{{ .Version }}-amd64"
  - "ghcr.io/tofutf/tofutf-agent:{{ .Version }}-arm64"
release:
  footer: |
    ## Docker images

    * `ghcr.io/tofutf/tofutfd:{{ .Version }}`
    * `ghcr.io/tofutf/tofutf-agent:{{ .Version }}`
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
