before:
  hooks:
    - make unit
builds:
  - id: otsd
    ldflags:
    - '-X ".Version={{ .Version }}"'
    - '-X ".Commit={{ .Commit }}"'
    main: ./cmd/otsd
    binary: otsd
    targets:
    - linux_amd64
    - darwin_amd64
archives:
- format: zip
  files:
  - none*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
