site_name: otf
theme: readthedocs
nav:
  - Home: index.md
  - install_from_source.md
  - install_from_helm_chart.md
  - Github: github.md
  - Agent: agents.md
  - client.md

markdown_extensions:
  - admonition
