name: releaser

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*


permissions:
  contents: read

jobs:
  publish:
    name: Publish Artifacts
    permissions:
      contents: write
      packages: write
      issues: write
      id-token: write
    runs-on: ubuntu-latest
    env:
      flags: ""
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      - name: Set up yq
        env: 
          VERSION: v4.34.2
          BINARY: yq_linux_amd64
        run: | 
          wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY}.tar.gz -O - |\
            tar xz
          sudo mv ${BINARY} /usr/bin/yq
      - uses: ko-build/setup-ko@3aebd0597dc1e9d1a26bcfdb7cbeb19c131d3037 # v0.7
      - name: publish-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          make publish VERSION=${{ github.ref_name }}
      - name: publish-snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: |
          make publish